### ISSUE TITLE
Create pig dice game html

### ISSUE THREAD

**Issue by ghost** [Keunyeong/ptdg#4]
## Tasks

- [x] Make dice button
- [x] Make next turn button
- [x] Add other tasks
